### ISSUE TITLE
Setup kanban board - final group capstone

### ISSUE THREAD

**Issue by lordksix** [Atril33/DocConnect-Backend#16]
Group members:
- @lordksix 
- @andrianarivo 
- @misalazeem 
- @Atril33 
- Link to the back-end repo: [here](https://github.com/Atril33/docconnect-backend)
- Link to the front-end repo: [here](https://github.com/Atril33/docconnect-frontend)
- Link to the project: [here](https://github.com/Atril33/docconnect-backend/projects/1)
- Screenshot of the project board:
![image](https://github.com/Atril33/DocConnect-Backend/assets/121689749/bb999c07-b4bc-44f3-b11f-00b943d134ea)

**Comment by Meltrust** [comment]
Hi @lordksix,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- The tasks have descriptions, assignees, and have been pointed✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
